# Generated by Django 5.1.5 on 2025-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='doi',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
