# Generated by Django 5.1.6 on 2025-02-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_project_doi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='additional_authors',
            field=models.ManyToManyField(blank=True, null=True, to='papers.author'),
        ),
    ]
