# Generated by Django 5.1.6 on 2025-07-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paper_unique_together_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='publication_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
