# Generated by Django 5.1.6 on 2025-07-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_publication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
