# Generated by Django 5.1.6 on 2025-02-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_author_alter_paper_doi_paper_additional_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='additional_authors',
        ),
        migrations.AddField(
            model_name='paper',
            name='additional_authors',
            field=models.JSONField(default=list),
        ),
    ]
