# Generated by Django 5.1.6 on 2025-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_project_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_master_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='submission_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
