# Generated by Django 5.1.6 on 2025-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_project_is_master_copy_project_submission_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_master_copy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='submission_year',
        ),
        migrations.AddField(
            model_name='paper',
            name='is_master_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='submission_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
