# Generated by Django 5.1.6 on 2025-10-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_remove_project_is_master_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='milestone_project',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
