# Generated by Django 5.1.6 on 2025-10-29 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_paper_milestone_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='author_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='is_master_copy',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='submission_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['doi', 'user'], name='papers_pape_doi_2630af_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['is_master_copy', 'user'], name='papers_pape_is_mast_dc16c2_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['submission_year', 'is_master_copy'], name='papers_pape_submiss_21f85d_idx'),
        ),
    ]
